---
- name: Create a network
  docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    driver_options: "{{ item.driver_options | default(omit) }}"
    internal: "{{ item.internal | default('no') }}"
    connected: "{{ item.containers  | default (omit) }}"
    ipam_config: "{{item.ipam_config | default(omit) }}"
  loop: "{{ docker_networks }}"
  when: docker_networks is defined
